### ISSUE TITLE
ImportError: cannot import name 'DuckDBCredentials' from 'dbt.adapters.duckdb.connections'

### ISSUE THREAD

**Issue by nzaw96** [godatadriven/dbt-excel#69]
Hi. I've installed dbt-excel in a new conda env and I'm getting the following error:

<img width="1415" alt="image" src="https://github.com/godatadriven/dbt-excel/assets/100609659/330c2563-a67e-47fc-8f37-e99e87815785">

I have the following dbt-* packages (I did NOT install them each separately. I only installed dbt-excel and the rest got installed as dependencies):
<img width="1400" alt="image" src="https://github.com/godatadriven/dbt-excel/assets/100609659/8e547882-e0ea-4e42-bccb-438ebfa3e3fa">

Here's what my profiles.yml looks like:
<img width="652" alt="image" src="https://github.com/godatadriven/dbt-excel/assets/100609659/b2fbe370-b79f-4d1e-af49-37fbb7c5a47a">

**Comment by JCZuurmond** [comment]
Hi, @nzaw96, we deprecated the `dbt-excel` project in favor of [`dbt-duckdb`](https://github.com/jwills/dbt-duckdb). It is a better maintained dbt adapter, and has capabilities to read from (since last release) and write to Excel files (in coming release).
